### PR TITLE
[WIP] Overhaul of the inner structure

### PR DESCRIPTION
**Pull request by coolwanglu**
This is (updating) snapshot of the current progress for the overhaul.

A few implementations are referred:
- `TextOutputDev` in poppler
- Tex
- llvm

Please review the files in `text/`, the idea is to store the text, shifts and styles in a more structural way, for the ease of debugging and further development.
The API is far from finished, but the overall framework is likely to be stable.

`TextPageBuilder` is supposed to be a minimal PDF-to-nodes converter, and _any_ further features will be implemented as a separate pass over the nodes. But if it turns out to be too slow in the future, we may optimize it when necessary.

Another things is, `boost::intrusive` is used for now. While I do not like to introduce new dependencies, this is a header-only library, which should be fairly easy to be included in the source tree if necessary.

@duanyao I hope that the new structure makes sense to you. For `--correct-text-visibility`, we may add additional fields for `TextChar` and process clips and images in `TextPageBuilder`. Or, we may add new types of Nodes and make a separate pass for this. All hidden characters should be removed from the structure, and we may collect the indices (indices are stored for each `TextChar`) for `BackgroundRenderers`. What do you think about it?

Please let me know if you have any comments.

### Possible passes over the data structure
- Detect and mark all the characters that are outside (or partial) the clip region, or covered (or partial) by images.
- Convert all characters with empty glyphs into offsets.
- Merge all consective offsets.
- Normalized all the matrices and sizes
- Group consective characters with same styles & matrices into words
  - A word should not contain any offset
- Group words with same styles & matrices into segments
- Group segments with same matrices into lines (or maybe paragraphs?)
- Output

### CODE REVIEW

**Comment by duanyao** [comment]
Some thoughts:
I think integrating `DrawingTracer` codes into `TextPageBuilder` is feasible, and putting `bbox` into `CharNode` is good.

However, I'd prefer one flatten array of `CharNode` for all chars in each page, rather than multi-level indirection (TextPage/TextSegment/TextWord/CharNode), because:

* Most post processing algorithms (such as text visibility checking, layout analysis) are bottom-up and only care about individual char's properties, so this indirection is not very useful to them.

* TextSegment/TextWord are built according to certain PDF drawing commands, but in many cases this is sub-optimal so we have `--optimize-text`. I believe an advanced optimization algorithm would unlikely rely on PDF drawing commands, and would rather build a new TextSegment/TextWord tree from bottom up by analyzing the array of `CharNode`.

So we can do this:
```
class CharNode
{
  ...
  TextStyle * style; // or int style_index, or merge TextStyle into CharNode
}
class TextPage
{
  vector<CharNode> chars;
  vector<TextStyle> styles;
  vector<TextSegment> segments;
}

TextWord
{
  ...
  int start; // starting index in TextPage::chars
  int end; // ending index in TextPage::chars
}
```

Another question: what's the advantage of `boost::intrusive::list` over `std:vector` ? Inserting/removing nodes seems rather rare, because during post processings we can (and probably prefer to) just build a new tree and drop the old one. P.S. I don't think "all hidden characters should be removed from the structure", because we want to output transparent texts for them (at least for partially visible chars), so setting a flag on invisible `CharNode` should be enough.

**Comment by coolwanglu** [comment]
The design of the hierarchy structures is toward thes HTML output, but not according to the PDF instructions. If the design does not reflect that, maybe something is still wrong with the design. In case you were mentioning the behavior of `TextPageBuilder`, it is supposed to convert/adapt the PDF instructions to our structures in an intuitive and fast way, such that we can start working on the structures as soon as possible. 

Yes I've been thinking about to continue using the flatten char array, just like the current design. But the problem I found is that we need to maintain lots of conditions manually. For example, if a `char` is removed (due to hidden by an image, or we decide to covert it to an offset), we need to find the `word` containing it and modify it accordingly. Then I was thinking, if we have to maintain this relationship of belonging, why don't we make it so in the structure and design API functions accordingly? This should be easier for others to understand and extend it, and potentially there could be fewer bugs.

Maybe you are right about most passes are char-wised, yet we may provide a char_iterator for `TextSegment`. The overhead should be small. In fact I had also considered the design of storing all the `char`'s in a list, and defining `TextWord`'s with two iterators, but in the end I thought that the benefit of iterating characters is not worth sacrificing a better set of APIs. At least we could write something like this:
```
for (auto & word : segment) {
  for (auto & c : word) {
    // do stuffs
  }
}
```


And about `vector` vs `list`. In the current design we are using indices as iterators, because `vector`'s iterators may be invalidated in lots of situations, and I found it ugly and error-prone to write code this way. There should less problems with `list`. And yes of course, we can always build a new array for each pass, but who is responsible to maintain the states, API designers or users? In the former case, I believe that the API could be complicated, and in the latter case (API designers can also be users here), the problem comes back again: the users have to carefully maintain the conditions while implementing the algorithm.

Generally I think for flatten-or-not, vector-or-list, both cases are equivalent in theory, but I would like to ease the process of implementing the passes on top of it.

**Comment by duanyao** [comment]
>For example, if a char is removed (due to hidden by an image, or we decide to covert it to an offset), we need to find the word containing it and modify it accordingly. 

Hidden char should not be removed, just marking it as "transparent" should be OK. Because text style is changed, the TextWord containing the hidden char have to be splitted, this seems complicated.

I'd recommend this workflow to avoid such mess:

1. Build an array of CharNode as well as an array of TextStyle while drawing a page.
    *  (Optional)  Run CovertedTextDetector during the drawing, and mark hidden chars in that array. We may push more TextStyles into the TextStyle array and let hidden chars reference them.
2. Do offset <-> space convertion/merging in the array of CharNode (implement offset as a special CharNode). Push more TextStyles if necessary.
3. Iterate over the array of CharNode, and group chars in a same line (according to x/y coordinate) and with same TextStyle into TextWords, put those TextWords into an array. Push more TextStyles if necessary.
4. Iterate over the array of TextWord, and group them into TextSegments, put those TextSegments into an array. Push more TextStyles if necessary.
5. Travelling the tree, generate HTML/CSS codes.
6. Draw background image, and draw hidden chars according to the array of CharNodes.

So we don't have to modify any TextWord/TextSegment/TextStyle but just build them, so iterator invalidation is not an issue.

This workflow is inspired by [PDFMiner](http://www.unixuser.org/~euske/python/pdfminer/index.html)'s layout analysis algoritm (which I had porting to C++).

**Comment by coolwanglu** [comment]
OK, that sounds good to me. So we do not restrict that the same structure is used in each pass, which makes sense here.

But during the offset<->space convertion, it is possible that we add more offsets in between in order to connect words. Of course we can do so by building a new array, but I'm thinking if it will be easy to do so.

Another problem is, right after we build `TextWord`, we need to make sure that the char array will never be modified, I'm not sure if this constraint is too strong. 

`std::list` or intrusive list may be used to solve both problems, I wonder if there are anything we need from `vector`?

**Comment by coolwanglu** [comment]
Oh, about transparent char, I was thinking of the case like this, suppose that we have "ABC", in which the letter B is covered by some image, then probably we will be able to merge A and C. But this could be edge cases.

I do not remember exactly which characters are shown, some characters are transparent as defined in PDF, and some are hidden due to overlapping. Shall we show both of them in HTML (transparently)?

**Comment by coolwanglu** [comment]
And about `inserting offset to connect words`, actually it can be done by adding a field `space_after` in the class `TextWord`, so right now I cannot think of a pass that inserting new elements in the array, which is good.

**Comment by duanyao** [comment]
>some characters are transparent as defined in PDF, and some are hidden due to overlapping. Shall we show both of them in HTML (transparently)?

We can add a flag to CharNode to distinguish them. However, it is quite hard to tell whether an char covered by an image is meaningless or not. It is also hard to tell whether an char is completely invisible -- what if the covering image is semi-transparent or clipped? So the safest way is to show all covered/clipped chars as transparent.

**Comment by duanyao** [comment]
>std::list or intrusive list may be used to solve both problems, I wonder if there are anything we need from vector?

Containers in STL are debugger friendly, I can view them in eclipse CDT or VC++, I'm not sure how about boost. I'd also prefer index over iterator, because during debugging I always know the progress of a iteration by check the value of the index.

Vector's other advantages are memory alloaction/dellocation speed and less memory fragment, this may be important or not. If the data structure is not quite dynamic, vector is prefered.

**Comment by coolwanglu** [comment]
I do think that intrusive list is an overkill here, it's just convenient for the prototype, my plan was to use `std::list` or our own implementations eventually. I will think again about `vector` vs `list`

And about the passes, I just realized that, if we dump all the chars first, we need to store all the styles for each char, the combine them by comparing the styles again. Could be a waste, but maybe it will be fast enough.

**Comment by coolwanglu** [comment]
I've listed all possible passes in my mind.  Please comment.

We could discuss the implementation accordingly.

**Comment by duanyao** [comment]
>if we dump all the chars first, we need to store all the styles for each char, the combine them by comparing the styles again

If we store a pointer or index to TextStyle in each CharNode, we can compare the pointer/index first, which should be fast. At least CharNodes generated by a single drawString() call share a same TextStyle object. If we merge TextStyle into CharNode, we can also add a flag inicating "has same style as last char".

**Comment by coolwanglu** [comment]
Yes, pointers to a style node would be a good solution.

**Comment by duanyao** [comment]
>And about inserting offset to connect words, actually it can be done by adding a field space_after in the class TextWord

I think this can also be done by adding all possible offsets in step 1. If we find some offsets that are not needed when building TextWord/TextSegment, just ignore them.

**Comment by coolwanglu** [comment]
I'm not sure if we can do so in step1, it depends on whether merging the word would need the information of the words. 

So after some thoughts, I decided to implement the char-vector with indices. Let's see if it will work well.

**Comment by duanyao** [comment]
I mean we can pre-allocate all possible offsets in step 1, so that don't have to insert offsets when we decide to merge words afterward.

**Comment by coolwanglu** [comment]
I think that it's not easy to do so, for example, supposed that we have two words "Hello World", which are drawn on the canvas with different matrices (I've seen PDF files which moves to positions by changing CTM). It is possible to check that the `o` and `W` may be connected by normalizing the matrices and then adding an offset in between.

However changing the styles on the char array might not be a good idea, usually style is used for one or more words, and I find it more natural to perform matrix-normalizing pass on the word array.

Currently the plan is to add 'shift_after_x' and 'shift_after_y' for each `Char` and `Word`. What're the benefits of Shift/Offset nodes over this design?

**Comment by duanyao** [comment]
When a char is to be appended to the CharNode array, unless we are sure that there is no preceding offset (e.g. "e" in "Hello World"), we always append an CharNode with "offset" type before that char (e.g. "W" in "Hello World"). If the width of the offset is yet to be determined, we can assgin 0 to it so that in following steps we can calculate the actual width.

There are quite a few chances that normal chars and offsets are converted to each other or even merged. E.g. illegals char may be converted to offsets and further merged with surrounding offsets/whitespaces. So I think is would be convenient that both normal chars and offsets are represented by CharNode so the convertion/merging can be done in-place.

As to styles, I think TextStyle can be made immutable. If we want to change a CharNode's style, we usually push a new TextStyle object into the per-page array of TextStyle, and modify the CharNode's style pointer to point to the new TextStyle. Unused TextStyles are not reclaimed until end of the renderring of the page, but this should not be a big problem.

**Comment by coolwanglu** [comment]
> There are quite a few chances that normal chars and offsets are converted to each other or even merged. E.g. illegal chars may be converted to offsets and further merged with surrounding offsets/whitespaces. So I think is would be convenient that both normal chars and offsets are represented by CharNode so the convertion/merging can be done in-place.

We may convert chars to offsets, but when shall we covert offsets to chars?

> As to styles, I think TextStyle can be made immutable. If we want to change a CharNode's style, we usually push a new TextStyle object into the per-page array of TextStyle, and modify the CharNode's style pointer to point to the new TextStyle. Unused TextStyles are not reclaimed until end of the renderring of the page, but this should not be a big problem.

By modifying styles, usually I meant re-scaling the matrix as well as the font size, or tweaking the positions, and most of time this happens word-wise. While you can covert style for individual chars, we will get lots of new duplicated styles, which is in my mind not natural or elegant.

An example of changing the styles: [...] & fs denote the CTM and font size
- [2,0,0,2,0,0] & 1 -> [1,0,0,1,0,0] & 2
So a ID matrix with font_size 2 is more natural than the former case, but there are lots of PDF doing the former way. In the old design, as well as the new one in my mind, whenever we change a style in this way, we should update all the elements using this style, instead of creating new styles for each of them. So the current design of `Segment` acts like a use-list for the style.

I'm considering removing the addition `shift` field in `Char`, leaving it only in `Word`. So `char->offset` means breaking a `Word` into two, and `offset->char` means merging two `Word`'s into one. How's that to you?

With this semantic, there could be even no need to actually merge the offsets in the char-array. We may simply do that in the word-array. In this way the char-array remain the same (but the individual chars may be modified). I really prefer iterators to indices.

About `Word`s, they may be allocated in buffers, but I think (intrusive) list might be better here as they are meant to be split or merged frequently.

**Comment by duanyao** [comment]
>We may convert chars to offsets, but when shall we covert offsets to chars?

Some PDFs use offsets instead of spaces. We may convert an offset between words to a space (or an offset containing a space).

>By modifying styles, usually I meant re-scaling the matrix as well as the font size, or tweaking the positions, and most of time this happens word-wise.

Because chars in a word have same style, we can only create a new TextStyle and update all CharNodes in the TextWord at once.

If the style duplication is really a problem, we can put TextStyle in a set instead of an array.

P.S. is it possible to keep font size constant globally, and only change the matrix? As I suggested in #369 .

>So char->offset means breaking a Word into two, and offset->char means merging two Word's into one.

You mean offsets can not live in Words? How about kerning?

I think now it is difficult to discuss more details before really implement it, so you may do it in your manner.

**Comment by coolwanglu** [comment]
OK, I'll finish it. In fact I found a few issues while using vector, I'm considering switching back.

**Comment by coolwanglu** [comment]
After a few attempts, I could not find a good solution, yet I realized that the benefit could be less than I had thought. So I'm closing it. However I will try to merge char, unicode and bbox together later.

**Pull request closed without merging**
